### ISSUE TITLE
08e951d causes 'NullObject' object has no attribute 'indirect_reference'

### ISSUE THREAD

**Issue by tigger0jk** [py-pdf/pypdf#3632]
I have some existing code that appends pages from a reader into a writer, and scales the new pages.

After https://github.com/py-pdf/pypdf/commit/08e951dea814420003d46d2f40a484b065e3ad76 this code throws an exception for specific problematic PDFs.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-14.6.1-arm64-arm-64bit-Mach-O

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==6.5.0, crypt_provider=('cryptography', '44.0.3'), PIL=11.3.0
# NOTE this actually fails on 6.6.0 and works fine on 6.5.0, I have isolated it to exactly the commit 08e951d that breaks it (before the 6.6.0 version bump)
```

## Code + PDF

Tragically, I cannot upload a PDF that breaks this, I have seen two so far, both contain client data and I have been unsuccessful in generating a sharable PDF that exhibits the same problem.

This is a minimal, complete example that shows the issue:

```python
import os
from pypdf import PdfReader, PdfWriter

input_path = "TODO_SET_INPUT_PATH.pdf"
output_path = "TODO_SET_OUTPUT_PATH.pdf"

def write_to_form(input_name: str, output_name: str):
    reader = PdfReader(input_name, strict=False)
    writer = PdfWriter()

    for i, page in enumerate(reader.pages):
        print(f"DEBUG - Adding page: {i}")
        # on page 2, we get: AttributeError: 'NullObject' object has no attribute 'indirect_reference' on this line
        writer.append(fileobj=reader, pages=[i], import_outline=False)
        # writer.add_page(reader.get_page(i)) # fails with the same end of the stack as the append call
        new_page = writer.pages[i]
        print(f"DEBUG - New page: {new_page}")

        # in the real flow, the point of this is to fix some PDFs before another scaling operation happens that would break them (I think because they don't have a mediabox?)
        # if you remove this line it works fine in 6.6.0
        new_page.scale_by(1)
        print(f"DEBUG - Scaled page: {new_page}")

    os.makedirs(os.path.dirname(output_name), exist_ok=True)
    with open(output_name, "wb") as output_stream:
        writer.write(output_stream)

    print(f"Wrote to {output_path}")

write_to_form(input_path, output_path)
```

## Traceback

This is the complete traceback I see (paths have been slightly modified and line numbers aren't identical for the reference code but the actual line contents are the same):

```
DEBUG - Adding page: 1
Traceback (most recent call last):
  File "/Users/pfay/pypdf_6_0_0_breakage.py", line 41, in <module>
    write_to_form(input_path, output_path)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pfay/pypdf_6_0_0_breakage.py", line 25, in write_to_form
    writer.append(fileobj=reader, pages=[i], import_outline=False)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pfay/.venv/lib/python3.13/site-packages/pypdf/_writer.py", line 2587, in append
    self.merge(
    ~~~~~~~~~~^
        None,
        ^^^^^
    ...<4 lines>...
        excluded_fields,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/pfay/.venv/lib/python3.13/site-packages/pypdf/_writer.py", line 2668, in merge
    srcpages[pg.indirect_reference.idnum] = self.add_page(
                                            ~~~~~~~~~~~~~^
        pg, [*list(excluded_fields), 1, "/B", 1, "/Annots"]  # type: ignore
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/pfay/.venv/lib/python3.13/site-packages/pypdf/_writer.py", line 605, in add_page
    return self._add_page(page, len(self.flattened_pages), excluded_keys)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pfay/.venv/lib/python3.13/site-packages/pypdf/_writer.py", line 508, in _add_page
    "PageObject", page_org.clone(self, False, excluded_keys).get_object()
                  ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pfay/.venv/lib/python3.13/site-packages/pypdf/generic/_data_structures.py", line 301, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields, visited)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pfay/.venv/lib/python3.13/site-packages/pypdf/generic/_data_structures.py", line 412, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pfay/.venv/lib/python3.13/site-packages/pypdf/generic/_data_structures.py", line 140, in clone
    arr.append(data.clone(pdf_dest, force_duplicate, ignore_fields))
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pfay/.venv/lib/python3.13/site-packages/pypdf/generic/_base.py", line 370, in clone
    assert dup.indirect_reference is not None, "mypy"
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NullObject' object has no attribute 'indirect_reference'
```

In order to determine the exact breaking change between 6.5.0 and 6.6.0 I  went through the commits in https://github.com/py-pdf/pypdf/compare/6.5.0...6.6.0 and found that I don't have any problems on https://github.com/py-pdf/pypdf/commit/8e1ccea7290cd4acec711170fdcb05bfaea8055b but when moving to https://github.com/py-pdf/pypdf/commit/08e951dea814420003d46d2f40a484b065e3ad76 I get the exception.

Specifically it's this exact change from that PR that if I undo it I don't get an exception and it works fine:
<img width="851" height="236" alt="Image" src="https://github.com/user-attachments/assets/f8f701cf-8bae-4936-ba25-10a2cc680adf" />
Also I don't see the deprecation warning right above it fire.

For now I am going to downgrade to pypdf 6.5.0 to avoid the problem. 

Please let me know if I can provide further information or test fixes, sorry I'm not able to include PDFs at this time.

**Comment by stefan6419846** [comment]
Thanks for the report. The mentioned offending line has never worked correctly, thus in theory the new approach should be more correct.

For further analysis, please provide a PDF file reproducing this issue and to ensure proper test coverage.

> Also I don't see the deprecation warning right above it fire.

I guess the page might not be part of the reader at this point any more, but without an example file, this is impossible to further analyze.

**Comment by tigger0jk** [comment]
I was able to find a PDF on the internet that exhibits this problem (not one of my documents): https://albneca.org/wp-content/uploads/2024/05/ML-4.30.24.pdf

In this document it actually seems to fail on adding the third page rather than the second.

I hope this is helpful.

**Comment by stefan6419846** [comment]
> Specifically it's this exact change from that PR that if I undo it I don't get an exception and it works fine:

This is because the old code would always run into an *AttributeError* due to `self._objects` only being defined on a `PdfWriter`, not on a `PageObject`, thus never doing anything useful.

The easiest solution seems to be to just replace `NullObject()` with `self.indirect_reference.pdf._add_object(NullObject())`, basically generating references to `null` objects instead of direct `null` objects.

Nevertheless, the approach of "deleting" an object by setting it to a `NullObject()` does not sound correct at all, although I am not sure how feasible "proper" deletion would be.

An alternative would be to replace the whole *for* loop with `cast(ArrayObject, self[PG.CONTENTS]).clear()` to remove the individual object references from the list and let you run `writer.compress_identical_objects(remove_orphans=True)` to actually remove the now obsolete objects.

**Comment by stefan6419846** [comment]
Okay, it is even weirder: Adding the indirect reference to the `NullObject` leads to `pypdf._page.PageObject.get_contents` emitting a warning from `pypdf.generic._data_structures.ContentStream.__init__` when applying the transformation:

> Expected StreamObject, got IndirectObject instead. Data might be wrong.

This is wrong as well and originates from us setting an indirect reference on the indirect reference.

It seems like I have found the correct solution with the following snippet:

```python
        writer = self.indirect_reference.pdf
        if isinstance(self.get(PG.CONTENTS, None), ArrayObject) and isinstance(writer, PdfWriter):
            content_array = cast(ArrayObject, self[PG.CONTENTS])
            for reference in content_array[:]:
                writer._replace_object(reference.indirect_reference, NullObject())
            content_array.clear()
```
